"""
LangGraph Workflow State Definition

Defines the state structure that flows through the 4-node workflow:
plan → retrieve → answer → reflect
"""

from typing import TypedDict, List, Dict, Any, Optional


class AgentState(TypedDict):
    """
    State dictionary passed between LangGraph nodes.

    Each node reads from and writes to this state, which flows through:
    PLAN → RETRIEVE → ANSWER → REFLECT
    """

    # Input
    question: str
    """The user's question/query"""

    # Conversation history (for multi-turn chat)
    chat_history: List[Dict[str, str]]
    """List of previous messages [{'role': 'user/assistant', 'content': '...'}]"""

    # Plan node output
    needs_retrieval: bool
    """Whether the question requires RAG retrieval (determined by plan node)"""

    # Retrieve node output
    retrieved_context: str
    """The concatenated context chunks retrieved from vector database"""

    retrieved_metadata: List[Dict[str, Any]]
    """Metadata for retrieved chunks (source, page, distances, etc.)"""

    # Answer node output
    answer: str
    """The final answer generated by the LLM"""

    # Reflect node output
    reflection: Dict[str, Any]
    """Evaluation/reflection results about the answer quality"""

    # Execution log (updated by all nodes)
    steps_log: List[str]
    """Log of each step's execution for debugging/transparency"""


def create_initial_state(question: str, chat_history: List[Dict[str, str]] = None) -> AgentState:
    """
    Create initial state for a new workflow run.

    Args:
        question: The user's question
        chat_history: Optional previous conversation history

    Returns:
        AgentState with question set and other fields empty/default
    """
    return AgentState(
        question=question,
        chat_history=chat_history or [],
        needs_retrieval=True,  # Default to True, plan node will decide
        retrieved_context="",
        retrieved_metadata=[],
        answer="",
        reflection={},
        steps_log=[]
    )


# Example usage
if __name__ == "__main__":
    # Create a sample state
    state = create_initial_state("What is a DDoS attack?")

    print("Initial State:")
    print(f"  Question: {state['question']}")
    print(f"  Needs Retrieval: {state['needs_retrieval']}")
    print(f"  Retrieved Context: '{state['retrieved_context']}'")
    print(f"  Answer: '{state['answer']}'")
    print(f"  Reflection: {state['reflection']}")
    print(f"  Steps Log: {state['steps_log']}")
